name : test
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - run: sudo apt-get update
      - run: sudo apt-get install dart
      - run: dart run main.dart

